# Generated by Django 3.0.3 on 2020-02-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200209_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='videofile',
            field=models.FileField(null=True, upload_to='movies/', verbose_name='Фильм'),
        ),
    ]
