# Generated by Django 3.0.3 on 2020-02-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20200213_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('date_addes', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
