# Generated by Django 3.0.3 on 2020-02-17 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_delete_movieusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='iframe',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='videofile',
        ),
    ]
