# Generated by Django 3.0.3 on 2020-02-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20200217_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos', verbose_name=''),
        ),
    ]
